server:
  port: 2672
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_my_show
    username: postgres
    password: rathoreji526
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    test-connection: true
    host: smtp.gmail.com
    port: 587
    username: movieplace38@gmail.com
    password: rcuw ssbh ziip tgah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true